;; C++ devel:
;; clangd server -> if it cannot find headers it probably needs a compile_commands.json files
;; that can be autogenerated with cmake with set(CMAKE_EXPORT_COMPILE_COMMANDS ON) at the start

(use-package lsp-mode
  :init
  ;; set prefix for lsp-command-keymap (few alternatives - "C-l", "C-c l")
  (setq lsp-keymap-prefix "C-c l")
  :bind (("C-p" . xref-pop-marker-stack)
	 ("C-n" . xref-find-definitions)
	 ("M-r" . lsp-find-references))
  :hook (;; replace XXX-mode with concrete major-mode(e. g. python-mode)
         (python-mode . lsp)
         (c++-mode . lsp)
         ;; if you want which-key integration
         ;; (lsp-mode . lsp-enable-which-key-integration)
				 )
  :config (setq
	   lsp-idle-delay 0.500
	   lsp-log-io nil
	   read-process-output-max (* 1024 1024))
  :commands (lsp lsp-deferred))

;; optionally
;; if you are helm user
(use-package lsp-ivy :commands lsp-ivy-workspace-symbol)

;; Suggestions from official docs for performance
(setq gc-cons-threshold 100000000)
(setq lsp-completion-provider :capf)
(setq lsp-idle-delay 0.500)
(setq lsp-log-io nil)

;; Annoying stuff
(setq lsp-enable-links nil)
(setq lsp-signature-render-documentation nil)
(setq lsp-headerline-breadcrumb-enable nil)
(setq lsp-ui-doc-enable nil)
(setq lsp-completion-enable-additional-text-edit nil)
